### ISSUE TITLE
An error occurs when pressing the right arrow key, left arrow key, etc.

### ISSUE THREAD

**Issue by tqkqt0** [attoae/quill-table-better#2]
An error occurs when pressing the right arrow key, left arrow key, etc. 
This can also be reproduced in CodePen. 
Since it occurs when pressing the key without inserting a table, a null check may be necessary.

```Uncaught runtime errors:
×
ERROR
Cannot read properties of null (reading 'next')
TypeError: Cannot read properties of null (reading 'next')
    at ht.makeTableArrowLevelHandler (http://localhost:3000/static/js/bundle.js:167359:18)
    at ht.handleKeyup (http://localhost:3000/static/js/bundle.js:167322:22)
    at Ve.handleKeyup (http://localhost:3000/static/js/bundle.js:170360:30)
ERROR
Cannot read properties of null (reading 'prev')
TypeError: Cannot read properties of null (reading 'prev')
    at ht.makeTableArrowLevelHandler (http://localhost:3000/static/js/bundle.js:167359:18)
    at ht.handleKeyup (http://localhost:3000/static/js/bundle.js:167322:22)
    at Ve.handleKeyup (http://localhost:3000/static/js/bundle.js:170360:30)
ERROR
Cannot read properties of null (reading 'parent')
TypeError: Cannot read properties of null (reading 'parent')
    at ht.makeTableArrowVerticalHandler (http://localhost:3000/static/js/bundle.js:167370:30)
    at ht.handleKeyup (http://localhost:3000/static/js/bundle.js:167326:22)
    at Ve.handleKeyup (http://localhost:3000/static/js/bundle.js:170360:30)```

**Comment by attoae** [comment]
This problem occurs when the table is incomplete. 
Did you delete the cells in some way?

**Comment by tqkqt0** [comment]
This occurs even when there is no table.
Currently, in my environment, this does not occur if I delete the following:
```
"table-better": {
language: l,
menus: ["column", "row", "merge", "wrap"],
},
```
It seems to occur if I add modules.

**Comment by attoae** [comment]
I will release the next version in the next two days and fix this issue.

**Comment by tqkqt0** [comment]
Thank you. I'm looking forward to it.
